title: CPU
description: Computing and Programming Union of Heriot-Watt University Malaysia

# disabled because we are using a custom domain
#baseurl: /business-frontpage

color-scheme: "#1572A1" # the scheme can be any HEX code like "#00aa55"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache
